//관심사 분리(?)를 적용해보았다. 그리고 상수는 관습상 대문자로 변수 이름을 선언한다.
export const ITEMLIST = [
  {
    id: 1,
    name: "Muse - BlackHole 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/Muse_BlackHole.jpeg",
    category: "album",
    userCart: false,
  },
  {
    id: 2,
    name: "Muse - Absol 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/Muse_Absolution.jpeg",
    category: "album",
    userCart: false,
  },
  {
    id: 3,
    name: "Luke - When 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/Luke_WhenFacing.jpeg",
    category: "album",
    userCart: false,
  },
  {
    id: 4,
    name: "검정치마 - 스페셜 앨범",
    price: 100000,
    like: false,
    cart: false,
    img: "./assets/images/albums/검정치마_Special.jpg",
    category: "album",
    userCart: false,
  },
  {
    id: 5,
    name: "검정치마 - TeamBaby 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/검정치마_TeamBaby.jpg",
    category: "album",
    userCart: false,
  },
  {
    id: 6,
    name: "GD - OneOfKind 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/GD_OneOfKind.webp",
    category: "album",
    userCart: false,
  },
  {
    id: 7,
    name: "GD - 무제 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/GD_2017.webp",
    category: "album",
    userCart: false,
  },
  {
    id: 8,
    name: "혁오밴드 - 1집 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/혁오_1집.jpg",
    category: "album",
    userCart: false,
  },
  {
    id: 9,
    name: "잔나비 - SeeYourEyes 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/잔나비_SeeYourEyes.jpg",
    category: "album",
    userCart: false,
  },
  {
    id: 10,
    name: "잔나비 - 전설 앨범",
    price: 50000,
    like: false,
    cart: false,
    img: "./assets/images/albums/잔나비_전설.webp",
    category: "album",
    userCart: false,
  },
  {
    id: 11,
    name: "인터스텔라",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/인터스텔라.jpg",
    category: "movie",
    userCart: false,
  },
  {
    id: 12,
    name: "인셉션",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/인셉션.jpg",
    category: "movie",
    userCart: false,
  },
  {
    id: 13,
    name: "노트북",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/노트북.jpg",
    category: "movie",
    userCart: false,
  },
  {
    id: 14,
    name: "어바웃타임",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/어바웃타임.webp",
    category: "movie",
    userCart: false,
  },
  {
    id: 15,
    name: "겨울왕국",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/겨울왕국.webp",
    category: "movie",
    userCart: false,
  },
  {
    id: 16,
    name: "조커",
    price: 12000,
    like: false,
    cart: false,
    img: "./assets/images/movies/조커.jpg",
    category: "movie",
    userCart: false,
  },
  {
    id: 17,
    name: "스위스 여행",
    price: 6000000,
    like: false,
    cart: false,
    img: "./assets/images/travels/스위스여행.jpg",
    category: "travel",
    userCart: false,
  },
  {
    id: 18,
    name: "미국 여행",
    price: 10000000,
    like: false,
    cart: false,
    img: "./assets/images/travels/미국여행.jpg",
    category: "travel",
    userCart: false,
  },
  {
    id: 19,
    name: "아마존 여행",
    price: 0,
    like: false,
    cart: false,
    img: "./assets/images/travels/아마존여행.jpg",
    category: "travel",
    userCart: false,
  },
  {
    id: 20,
    name: "제주도 여행",
    price: 500000,
    like: false,
    cart: false,
    img: "./assets/images/travels/제주도여행.jpg",
    category: "travel",
    userCart: false,
  },
  

]